// <auto-generated />
using Hackathon_2025_Filipino_Homes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hackathon_2025_Filipino_Homes.Migrations
{
    [DbContext(typeof(HackathonContext))]
    [Migration("20250414053922_Bounty model change 2.0")]
    partial class Bountymodelchange20
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hackathon_2025_Filipino_Homes.Models.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BountyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BountyId")
                        .IsUnique()
                        .HasFilter("[BountyId] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("account");
                });

            modelBuilder.Entity("Hackathon_2025_Filipino_Homes.Models.Bounty", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("reward")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("bounty");
                });

            modelBuilder.Entity("Hackathon_2025_Filipino_Homes.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Hackathon_2025_Filipino_Homes.Models.Account", b =>
                {
                    b.HasOne("Hackathon_2025_Filipino_Homes.Models.Bounty", "bounty")
                        .WithOne("account")
                        .HasForeignKey("Hackathon_2025_Filipino_Homes.Models.Account", "BountyId");

                    b.HasOne("Hackathon_2025_Filipino_Homes.Models.User", "user")
                        .WithOne("account")
                        .HasForeignKey("Hackathon_2025_Filipino_Homes.Models.Account", "UserId");

                    b.Navigation("bounty");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Hackathon_2025_Filipino_Homes.Models.Bounty", b =>
                {
                    b.Navigation("account");
                });

            modelBuilder.Entity("Hackathon_2025_Filipino_Homes.Models.User", b =>
                {
                    b.Navigation("account");
                });
#pragma warning restore 612, 618
        }
    }
}
